version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nest_app_pnpm
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3000}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      # DATABASE_URL: ${DATABASE_URL}
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nestapp_network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres_db_pnpm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_pnpm:/var/lib/postgresql/data
    networks:
      - nestapp_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  nestapp_network:
    driver: bridge

volumes:
  postgres_data_pnpm:
